[phases.setup]
nixPkgs = ["ffmpeg"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
  "touch database/database.sqlite",
  "php artisan key:generate --force",
  "php artisan migrate --force"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
